site_name: SE311 - Sillah (صلة) Family Health Management System
site_description: Full SE311 Software Requirements Analysis Project Documentation
site_url: https://Software-Requirements-Analysis.Shoug-Tech.com

theme:
  name: material
  icon:
    logo: material/ambulance
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Team: team.md

  - Phase 1 - Inception:
      - Overview: Phase 1 - Inception/index.md
      - Business Requirements: Phase 1 - Inception/business-requirements.md
      - Scope & Limitations: Phase 1 - Inception/scope-and-limitations.md
      - Business Context: Phase 1 - Inception/business-context.md

  - Phase 2 - Elicitation:
      - Overview: Phase 2 - Elicitation/index.md
      - Stakeholders: Phase 2 - Elicitation/stakeholders.md
      - Elicitation Plan: Phase 2 - Elicitation/elicitation-plan.md
      - Elicitation Notes: Phase 2 - Elicitation/elicitation-notes.md

  - Phase 3 - Analysis:
      - Overview: Phase 3 - Analysis/index.md
      - Domain Model: Phase 3 - Analysis/domain-model.md
      - Use Cases: Phase 3 - Analysis/use-cases.md
      - Functional Requirements: Phase 3 - Analysis/functional-requirements.md
      - Non-Functional Requirements: Phase 3 - Analysis/nonfunctional-requirements.md
      - Prioritization: Phase 3 - Analysis/prioritization.md

  - Phase 4 – Specification:
      - Overview: Phase 4 – Specification/index.md
      - SRS: Phase 4 – Specification/srs.md

  - Phase 5 – Validation:
      - Overview: Phase 5 – Validation/index.md
      - Validation Results: Phase 5 – Validation/validation-results.md

  - Phase 6 – Requirements Management:
      - Overview: Phase 6 – Requirements Management/index.md
      - Change Control: Phase 6 – Requirements Management/change-control.md
      - Traceability Matrix: Phase 6 – Requirements Management/traceability-matrix.md


  - Report:
      - View & Download: report/report.md

  - Conclusion: conclusion.md


markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html

extra_css:
  - styles/extra.css